__author__ = 'abilgin'

COLLECTION = "configurations"

DEFAULT_CORPUS_LIST = "COHA"
DEFAULT_GENRE = "news"
DEFAULT_BIN_INTERVAL = 10
DEFAULT_NGRAM = "unigram"

DEFAULT_TRAINING_ALG = "SGNS"
DEFAULT_NEGATIVE = 5
DEFAULT_DIMENSIONS = 100
DEFAULT_WINDOW_SIZE = 4
DEFAULT_ITER = 5
DEFAULT_SAMPLE = 0
DEFAULT_MIN_COUNT = 5